"""PLANO GLOBAL DA TESE — planejamento metodológico ANTICIPADO, como dado estruturado.

Single-source OO: este módulo alimenta (1) o render PLANO_GLOBAL_DA_TESE.md (humano),
(2) a tabela PlanChapter no SQLite (query), (3) o gate G7 (plan↔realizado).
Fundamentado em: section_blueprints B0–B9 · writing_rationale_matrix R0–R9 ·
style_profile · KNOWLEDGE_CANON (grafo) · THESIS_ROADMAP · paper_spine_config.
"""

# ============ NÍVEL GLOBAL ============

ORDEM_LOGICA = [
    ("c01", "nomear+diferenciar", "sem nome aceito, nada é discutível — a 'chave-antes-da-porta'"),
    ("c02", "contrato formal", "define O QUE se promete (questões/objetivos/hipóteses/M1–M5) antes de qualquer evidência"),
    ("c03", "plausibilidade", "por que acreditar que é possível (literatura) — antes de gastar simulação"),
    ("c04", "a ponte", "mesmos dados sob fundamento e aplicação + validação M3→M2 + cronologia honesta (anti-hindsight EXIBIDO como força)"),
    ("c05", "o alicerce", "invariância θ* multi-espécie: SEM ela, a aplicação não emerge — precede e legitima c06"),
    ("c06", "o produto", "o desenho terapêutico EMERGE (transporte→limiar→dose banda GUM→G0-wet→custo)"),
    ("c07", "auditabilidade", "método formalizado P0–P6: examinador audita 'trocando só termos' (H1)"),
    ("c08", "validação", "cada resultado valida UMA promessa (regra V4) — nada órfão"),
    ("c09", "novidade", "o que é novo (cura+restauração), replicável AD/PD, próximas abordagens declaradas"),
    ("c10", "significado", "o que os resultados significam E o que não significam"),
    ("c11", "tradução clínica", "acessibilidade médica: leitura-10min, o incomum explicado a médicos"),
    ("c12", "limites-como-fruto", "cada limitação com o gate que a fecha (JHU-iii)"),
    ("c13", "fechamento", "veredito por objetivo OE1–OE4"),
]

VALOR_RANKING = [
    (1, "θ*=0,333 invariante multi-espécie (c05)", "alicerce: tudo deriva dela; cenário B 0,333–0,400 ×4 espécies"),
    (2, "A primeira dose calculada — banda GUM A6 (c06)", "produto nunca feito; 'a largura ≈53× É o achado' — honestidade quantificada"),
    (3, "O método etrização (c01/c07)", "nomeável, auditável, transferível para AD/PD — contribuição metodológica perene"),
    (4, "Cura+restauração (achado único, c09)", "conteção E reversão de dano: além de qualquer terapia priônica existente"),
    (5, "Infraestrutura M1–M5 (c08)", "θ_obs/freeze/re-param/seleção-parceiro/continuidade — replicabilidade institucional"),
]

GARANTIAS = [
    ("Cronologia honesta (predições v1.0 travadas ANTES da Parte 3)", "garante anti-hindsight", "→ valida M3→M2 como emergência lógica, não ajuste ad hoc"),
    ("Cadeia sha256 (claims norm→hash; JSONs idênticos Colab≡repo)", "garante integridade dos números", "→ gate F1/F3 do engine a espelham"),
    ("Tiers [SIM]/[ORGANOID] em toda saída de dose", "garante honestidade epistêmica (não-promessa)", "→ gate G3"),
    ("Base comum (mesmos dados M2=M3)", "garante que o desenho EMERGE do fundamento", "→ tabela §4.3"),
    ("G0-wet especificado c/ kill-switch + SAP cego", "garante falsificabilidade programática", "→ negative-result é resultado válido"),
    ("Concordância claims↔referências 58/58", "garante rastreabilidade total", "→ régua: claim sem referência é inaceitável"),
]

INCOMUM_PARA_MEDICOS = [
    "Dominante-negativo por COMPETIÇÃO, sem silenciar o alelo nativo (vs terapias de silenciamento — o nativo segue funcionando)",
    "Dose como BANDA com incerteza GUM propagada, não número único — 'a largura da banda é o achado até G0-A6'",
    "Prognóstico calculado ANTES da medição: decidir o que medir/onde/em que dose antes de gastar wet-lab (etrização)",
    "Horizonte de observação como parte da dose (dependência de horizonte: o número só compara sob horizonte declarado)",
    "Titulação por cinética do paciente (Kt em classes 1–4): dose personalizada por subtipo — não há 'a dose', há a escada",
]

PRE_DEFINIR = [
    "nomenclatura θ* (limiar travado) vs θ (funcional) · κ adimensional · Kt em classes 1–4 (nunca contínuo)",
    "tiers [SIM]/[SIM]-planejamento/[ORGANOID] + tríade não-promessa (título de figura + tabela + claim)",
    "decimais: vírgula PT-BR no corpo; ponto só nas claims EN canônicas (norm→sha256)",
    "cronologia: predições v1.0 de 26/08 NUNCA retreinadas; Parte 3 declarada como força",
    "voz: agente é 'o programa/a tese/o desenho'; a autora aparece como validadora expressa",
]

# ============ NÍVEL POR CAPÍTULO (17) ============
# campos: key, ordem, funcao, objetivo, fontes[{tipo,ref}], topicos, elementos,
#         complicado, simplificar

PLANO_CAPITULOS = [
    dict(key="c00", ordem=0, funcao="contrato de leitura",
         objetivo="Declarar título-promessa e dar os instrumentos de navegação (resumo, sumário, siglas).",
         fontes=[dict(tipo="doc", ref="style_profile.md · paper_spine_config.md")],
         topicos=["RESUMO/ABSTRACT (contribuição em 1 parágrafo)", "SUMÁRIO", "LISTA DE SIGLAS"],
         elementos=["siglas upfront"],
         complicado="densidade terminológica (θ*, κ, Kt, G0, tiers)",
         simplificar="LISTA DE SIGLAS antes do Cap.1 + âncoras verbais ('1/3 sobrevive')"),
    dict(key="c01", ordem=1, funcao="nomear+diferenciar (M1)",
         objetivo="Responder 'por que etrização, e o que a diferencia' ANTES de qualquer conteúdo técnico.",
         fontes=[dict(tipo="doc", ref="ERITRIZACAO.md (câmara de fundamentação)"),
                 dict(tipo="claim", ref="C054 (definição operacional)"),
                 dict(tipo="grafo", ref="comunidade 'Etrização Framework (Philosophy)'")],
         topicos=["3 camadas semânticas do radical", "definição operacional C054",
                  "vs in-silico trials (simulam o ENSAIO; etrização simula a CONTINUAÇÃO)",
                  "vs revisão sistemática/meta-análise (resumem; etrização DERIVA)"],
         elementos=["tabela 3-colunas de contraste"],
         complicado="abstração filosófica de um nome novo",
         simplificar="analogia do átomo (palavra que fundou 2.400 anos de pesquisa antes da prova) + tabela de contraste"),
    dict(key="c02", ordem=2, funcao="contrato formal",
         objetivo="Fixar problema→justificativa→questões→objetivos(OE1-4)→hipóteses(H1-3)→componentes M1–M5.",
         fontes=[dict(tipo="doc", ref="m3_to_m2_validation.md §1"), dict(tipo="db", ref="claims seção 2.x")],
         topicos=["2.1 problema", "2.2 justificativa", "2.3 questões", "2.4 objetivos+OE",
                  "2.5 hipóteses", "2.6 estrutura", "2.7 tabela M1–M5 validada pela autora"],
         elementos=["tabela-mãe M1–M5 (validada)"],
         complicado="cruzamento OE×H×M1–M5",
         simplificar="uma única tabela-mãe; cada OE liga a 1 hipótese e a componentes nomeados"),
    dict(key="c03", ordem=3, funcao="plausibilidade",
         objetivo="Mostrar que o gargalo priônico é real e que a família antecipatória tem berth (posição H3).",
         fontes=[dict(tipo="doc", ref="literature/evidence_table.md E001–E029"),
                 dict(tipo="grafo", ref="comunidades 'Prion Literature Evidence Table' · 'Neuro-Disease Precedents'"),
                 dict(tipo="figura", ref="Fig.1 mapa científico")],
         topicos=["3.1 gargalo terapêutico", "3.2 família dos métodos antecipatórios/in-silico",
                  "3.3 posicionamento da etrização (H3)", "3.4 fundamento epistemológico", "3.5 síntese"],
         elementos=["Fig.1 — mapa científico em camadas"],
         complicado="28 fontes heterogêneas (genética→estrutural→organoides→regulatório)",
         simplificar="mapa em camadas (Fig.1): cada achado vira um pino no mapa, não uma seção"),
    dict(key="c04", ordem=4, funcao="a ponte M3↔M2 — linha experimental",
         objetivo="Mesmos dados sob os dois módulos + LINHA EXPERIMENTAL: experimento 1 (murino+humanização, θ* travado) → por que otimizamos (segurança: uma espécie não orquestra certeza) → experimento 2 multi-espécie = A BASE DA TESE (exp1 só onde inalterado); anti-hindsight substantificável PELO DOCUMENTO (pré-registros citados e reproduzidos em anexo — nunca aponte ao repo).",
         fontes=[dict(tipo="doc", ref="m3_to_m2_validation.md §§1-2"),
                 dict(tipo="json", ref="p024_{mouse,hamster,human,vole}.json · species_params.json"),
                 dict(tipo="claim", ref="C013 · C032 · C055 · C056 · C057 · C040")],
         topicos=["4.1 a mesma base sob os dois módulos",
                  "4.2 linha experimental: experimento 1 → otimização → experimento 2 (a base da tese)",
                  "4.3 tabela de validação (todos os números via claims do registro)"],
         elementos=["tabela de validação com vereditos ✅"],
         complicado="duas execuções experimentais sem virar duas teses",
         simplificar="narrativa única: exp1 = fase de segurança; exp2 = a tese; inalterância do exp1 atestada pelas mesmas claims"),
    dict(key="c05", ordem=5, funcao="o alicerce (M3)",
         objetivo="Estabelecer a invariância de θ* multi-espécie, a regra de titulação e a dependência de horizonte.",
         fontes=[dict(tipo="json", ref="p024_{mouse,hamster,human,vole}.json"),
                 dict(tipo="claim", ref="C055–C057 · N055–N059"),
                 dict(tipo="canon", ref="F-44 · H-P3 · THETA_STAR_EXPLAINED (grafo Guardian Integrity)"),
                 dict(tipo="figura", ref="Fig.4")],
         topicos=["5.1 sweep→parametrização por espécie", "5.2 Cenário B [SIM]",
                  "5.3 regra de titulação emergente (Kt 1→1,5·2→2·3→3·4→8)",
                  "5.4 dependência de horizonte (a única assimetria real; hamster refutado honestamente)"],
         elementos=["Fig.4 θ* por espécie", "tabela bandas A–D"],
         complicado="4 espécies × bandas-Kt × horizonte simultâneos",
         simplificar="Fig.4 escada por espécie com banda sombreada + âncora verbal única ('1/3 sobrevive no pior dia')"),
    dict(key="c06", ordem=6, funcao="o produto (M2)",
         objetivo="Derivar o desenho terapêutico: transporte→limiar travado→primeira dose em banda GUM→G0-wet→custo.",
         fontes=[dict(tipo="json", ref="m31_u1u2.json (u1_kreq·chain·u2_mw 22,83 kDa) · ws_7_results.json"),
                 dict(tipo="claim", ref="C033/C038/C040/C051 · C058–C060 · E057/E058 · N060–N065"),
                 dict(tipo="figura", ref="Fig.5 escada de dose")],
         topicos=["6.1 três regras de transporte falseáveis", "6.2 limiar travado e dose legitimada pela banda",
                  "6.3 a PRIMEIRA dose calculada (cadeia κ→µM→µg/depósito GUM) [SIM]-planejamento",
                  "6.4 G0-wet especificado (8 braços, SAP Welch/Holm cego, kill-switch)", "6.5 custo-cotação S1"],
         elementos=["tabela escada Kt×κ (≤5 col)", "Fig.5 com pior-caso hachurado", "tabela S1 custo"],
         complicado="cadeia dimensional κ_req→µM→µg com incerteza Tipo-B por el",
         simplificar="Fig.5 escada-de-dose (bandas explícitas, hatch no pior-caso) + mantra: 'a largura ≈53× É o achado até G0-A6'"),
    dict(key="c07", ordem=7, funcao="auditabilidade (B5)",
         objetivo="Formalizar a etrização P0–P6 com garantias por passo e Base de Validade de linhagem completa.",
         fontes=[dict(tipo="doc", ref="guardian decálogo · AST 9/9 · C046/C052–C054"),
                 dict(tipo="grafo", ref="comunidades 'guardian.py Rounds Engine' · 'ast_check.py Validation Suite'")],
         topicos=["7.0 pipeline P0–P6 (diagrama)", "7.1 o método nomeado", "7.2 formulação matemática COM proveniência",
                  "7.3 Base de Validade (mandatória)", "7.4 a tese em forma experimental (mapeamento análogo)"],
         elementos=["diagrama pipeline §7.0", "equações cada uma com citação de origem"],
         complicado="formalismo matemático denso",
         simplificar="opener 'rastreio farmacocinético' + diagrama do pipeline + equação-com-proveniência (nunca equação nua)"),
    dict(key="c08", ordem=8, funcao="resultados-como-validação (V4)",
         objetivo="Cada resultado valida UMA promessa; apresentar M1–M5 como resultados (não como planos).",
         fontes=[dict(tipo="doc", ref="results_validation.md"), dict(tipo="json", ref="part2_theta_obs_*.json · E032/E033")],
         topicos=["8.1 resultados da simulação JÁ realizada", "8.2 M1 θ_obs", "8.3 M2 freeze",
                  "8.4 M3 loop anti-hindsight", "8.5 M4 seleção de parceiro (SLR-análogo)", "8.6 M5 continuidade"],
         elementos=["tabela promessa↔resultado↔registro"],
         complicado="mapeamento 1:1 promessa-resultado",
         simplificar="tabela de mapeamento explícita — nenhuma subseção métrica órfã (gate V4)"),
    dict(key="c09", ordem=9, funcao="novidade explícita",
         objetivo="Nomear o achado único (cura+restauração), a replicabilidade (AD/PD) e as próximas abordagens.",
         fontes=[dict(tipo="doc", ref="5.1-bis/5.2-bis · F-44"), dict(tipo="grafo", ref="comunidade 'Population Impact & Trials'")],
         topicos=["9.1 achados e impactos", "5.1-bis cura+restauração", "9.2 áreas correlatas",
                  "5.2-bis replicabilidade AD/PD", "9.3 próximas abordagens (declaração mandatória)"],
         elementos=["—"],
         complicado="escopo além de priões pode soar promessa",
         simplificar="declaração mandatória de próximas abordagens + tiers em tudo"),
    dict(key="c10", ordem=10, funcao="significado com limites",
         objetivo="Dizer o que os resultados significam E o que não significam.",
         fontes=[dict(tipo="doc", ref="hostile_review_v4 · guardian reports E-01..23")],
         topicos=["10.1 promessas e limites da Parte 2", "10.2 significa/não-significa"],
         elementos=["estrutura binária significa|não-significa"],
         complicado="tom entre promessa e não-promessa",
         simplificar="estrutura binária explícita em duas colunas"),
    dict(key="c11", ordem=11, funcao="tradução clínica (B7)",
         objetivo="Acessibilidade médica total: leitura-10min, linguagem clínica, acompanhamento previsto.",
         fontes=[dict(tipo="doc", ref="AVALIACAO_ALFA convergências · E019 LNP · E039 turnover · E034–38 ensaios")],
         topicos=["NOTA DE LEITURA (5 perguntas + caixa de aviso)", "resumo-1página rota-10min",
                  "openers 'Em linguagem clínica:'", "acompanhamento previsto [SIM] (desenho, NÃO conduta)"],
         elementos=["caixa de aviso", "tabela acompanhamento [SIM]", "Fig.4 no leito clínico"],
         complicado="farmacocinética/toxicologia para não-especialista",
         simplificar="openers analógicos ('rastreio farmacocinético') + 5 perguntas de leitura + rota de 10 minutos"),
    dict(key="c12", ordem=12, funcao="limitações-como-fruto (JHU-iii)",
         objetivo="Cada limitação nomeada COM o gate/ensaio que a fecha — limite como agenda.",
         fontes=[dict(tipo="doc", ref="guardian findings E-01..23 · C043"), dict(tipo="grafo", ref="'Negatives & Appendix Anchors'")],
         topicos=["classes: transferência/horizonte/preprints-monitorados/localização/imunogenicidade", "cada limite → o que fecha"],
         elementos=["tabela limite↔fecho"],
         complicado="15+ limitações",
         simplificar="agrupar por classe + coluna única 'o que fecha isto'"),
    dict(key="c13", ordem=13, funcao="fechamento por objetivo",
         objetivo="Veredito por OE1–OE4, cada um ancorado nas claims correspondentes.",
         fontes=[dict(tipo="db", ref="claims por OE · tabela §2.7")],
         topicos=["OE1 nomear/formalizar", "OE2 Base de Validade", "OE3 resultados-como-achados", "OE4 continuidade documentada"],
         elementos=["um parágrafo-veredito por OE"],
         complicado="—",
         simplificar="estrutura fixa por OE: prometido→entregue→onde"),
    dict(key="c14", ordem=14, funcao="rastreabilidade ABNT",
         objetivo="58 fontes do registro em ABNT, citadas 58/58.",
         fontes=[dict(tipo="db", ref="source_manifest.json (E001–E058)")],
         topicos=["58 referências", "fontes complementares (verificação pendente — snippet)"],
         elementos=["gerada do registro (engine)"],
         complicado="duplicação/ordem ABNT",
         simplificar="geração determinística do registro; zero digitação"),
    dict(key="c15", ordem=15, funcao="inventário verificável",
         objetivo="Todo artefato da Parte 2 listado em disco + concordância claims↔referências completa.",
         fontes=[dict(tipo="doc", ref="artifact_check.md · claim_register.md")],
         topicos=["inventário A", "concordância claims→referências (régua da autora)"],
         elementos=["tabela concordância 60 claims × fontes"],
         complicado="60×N cruzamento",
         simplificar="tabela gerada do grafo (engine) — o gate G7 a valida"),
    dict(key="c16", ordem=16, funcao="mapa da lógica",
         objetivo="De onde veio cada informação e como se conecta; decisões, rejeições, glossário, objeções.",
         fontes=[dict(tipo="grafo", ref="todo o grafo dos 3 trees"), dict(tipo="doc", ref="guardian decisions/rejeições")],
         topicos=["B.1 fluxo informação literatura→conclusão", "B.2 decisões-chave (por quê)",
                  "B.3 rejeições documentadas (o que NÃO funcionou)", "B.4 glossário contextual", "B.5 prejulgando objeções da banca"],
         elementos=["fluxograma B.1", "tabela de rejeições B.3"],
         complicado="proveniência total é o maior grafo",
         simplificar="um mapa único: cada afirmação da tese rastreável a arquivo/claim/JSON (o engine já faz isto — expor como figura)"),
]
