#!/usr/bin/env python3
"""Gera o PDF do preprint (manuscrito v2) via reportlab — bioRxiv-ready.
Uso: /workspace/.venv-numpy/bin/python build_pdf.py"""
import os, re
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

HERE=os.path.dirname(os.path.abspath(__file__))
OUT=os.path.join(HERE,'preprint_v3_quest003.pdf')

INK=HexColor('#1a1a2e'); MUT=HexColor('#555577'); ACC=HexColor('#0f6b4f')
ss=getSampleStyleSheet()
S_title=ParagraphStyle('t',parent=ss['Title'],fontName='Helvetica-Bold',fontSize=16,leading=20,textColor=INK)
S_aut=ParagraphStyle('a',parent=ss['Normal'],fontSize=9.5,textColor=MUT,alignment=1,leading=13)
S_h1=ParagraphStyle('h1',parent=ss['Heading1'],fontName='Helvetica-Bold',fontSize=12.5,leading=15,textColor=ACC,spaceBefore=12,spaceAfter=4)
S_h2=ParagraphStyle('h2',parent=ss['Heading2'],fontSize=10.5,leading=13,textColor=INK,spaceBefore=8,spaceAfter=3)
S_body=ParagraphStyle('b',parent=ss['Normal'],fontSize=9.6,leading=13.6,alignment=4,textColor=INK)
S_ref=ParagraphStyle('r',parent=ss['Normal'],fontSize=8.2,leading=11,textColor=MUT,leftIndent=10)
S_abs=ParagraphStyle('ab',parent=S_body,fontSize=9.2,leading=13,leftIndent=16,rightIndent=16,textColor=MUT)

story=[]
def P(t,st=S_body): story.append(Paragraph(t,st))
def SP(h=4): story.append(Spacer(1,h))

def fmt(t):
    t=re.sub(r'\*\*(.+?)\*\*',r'<b>\1</b>',t)
    t=re.sub(r'\*(.+?)\*',r'<i>\1</i>',t)
    t=t.replace('V127ΔGPI','V127ΔGPI').replace('→','&rarr;').replace('≥','&ge;').replace('≤','&le;').replace('×','&times;').replace('~','~')
    return t

P('PrP-V127 as a Modular Antiprion Platform: Therapeutic Vectors, Tissue-Scale Transport Design, and Regulatory Precedents for Creutzfeldt-Jakob Disease',S_title)
SP(6)
P('Consórcio de Investigação em Príons e Engenharia Molecular (open-science initiative) · DeepScientist Quest 003 · Preprint v2.0 — 2026-08-26',S_aut)
P('<i>Draft for bioRxiv deposition — establishes priority of the secretor/mRNA vector designs and design rules described herein.</i>',S_aut)
SP(8)

P('Abstract',S_h1)
P(fmt('Prion diseases are fatal with no approved therapy. The human PrP variant G127V, selected during the kuru epidemic, confers complete prion resistance and acts as a potent dominant-negative inhibitor of wild-type propagation — including as a GPI-anchorless, secreted protein in trans (in vitro 2026; AAV proof-of-concept in rodents 2026). We present a structured preclinical review and research program that converts this molecular asset into a deployable therapy for CJD. (1) **Vectors:** we audit three delivery modalities for the anchorless V127 agent — CRISPR-edited neural progenitor secretory grafts, recombinant protein, and intrathecal LNP-mRNA — with pre-registered go/no-go gates in sCJD-infected human cerebral organoids (platform validated: infection 2019; PPS drug screening 2021; NPC seeding 2023; V127 in any form never tested). (2) **Transport design:** a self-tested advection-diffusion-reaction solver (mass conservation 100%; Thiele-length error 0.5%) yields three falsifiable design rules — containment-ring node spacing 8-12 mm; hydrogel carrier mesh &xi; &ge; 5&times; the protein radius (hyaluronic acid 1-2% approved, &gt;5% retains the secretome); mRNA redosing &le; 7 days; and a containment shell of 4.2-9.5 mm per deposit depending on the capping/replication ratio, a parameter directly measurable in the proposed organoid assay. (3) **Regulatory precedents:** by analogy to sister proteinopathies, no pillar requires an unprecedented regulatory category — chronic intrathecal redosing (SMA/nusinersen), accelerated approval via biomarker in lethal genetic neurodegeneration (SOD1-ALS/tofersen, NfL), cell grafts in human brain (Parkinson 2026), dominant stabilization of a misfolding-prone native protein (TTR/tafamidis), and substrate silencing (ASO/RNAi) are all approved categories whose conjunction this program requests. We conclude that anchorless-V127 antiprion therapy is publishable now as a program and testable within one organoid cycle (~10 months), with realistic endpoints of significant slowing (structured estimate 30-45%) rather than cure.'),S_abs)
SP(6)

P('1. Background and scope',S_h1)
P(fmt('CJD is uniformly fatal within months (sporadic) although genetic carriers (E200K, D178N, P102L) afford a presymptomatic window of years — the population where autologous, time-permissive protocols are feasible; a first E200K kindred in Brazil was reported in 2007. This manuscript integrates: a 41-reference audited review (including correction of recurring citation errors in the field), refutation-driven solution branches, quantitative transport engineering, and a regulatory analogy map. It is the program-level companion to the organoid gate protocol (G0).'))
P('2. The molecular asset and its three vectors',S_h1)
P(fmt('G127V: complete resistance when biallelic (heterozygotes remain infectable by vCJD — hence biallelic editing or anchorless delivery is mandatory); structural basis twofold (conformational restriction of the pre-&beta; sheet, dimer stabilization via intermolecular H-bonds, &beta;2-&alpha;2 loop dynamics). Dominant-negative effect: dose-dependent in cis; **and in trans as recombinant anchorless protein (2026), with protection persisting after transgene cessation** — the property that makes transient vectors (mRNA) viable and reduces dependence on permanent "factory" designs. In vivo proof-of-concept: systemic AAV delivering anchorless V127 extended survival ~50 days in a rodent model.'))
P(fmt('Vectors: **(a) Secretory neural progenitor grafts** (CRISPR biallelic V127 + &Delta;GPI secretion; optional iPSC-microglia co-graft for phagocytic support; hypommune HLA-KO+CD47 platform for off-the-shelf banking); **(b) recombinant anchorless V127 protein** (direct chemical comparability with the 2026 in vitro data); **(c) intrathecal LNP-mRNA** (expression in ~30% neurons / 38% astrocytes after a single intrathecal dose in rodents; manufacturing in days — the only vector compatible with compassionate use in sporadic CJD timelines).'))
P('3. The organoid gate (G0): pre-registered falsifiability',S_h1)
P(fmt('Eight arms, n=8 organoids/arm, ~10-month cycle, BSL-3: A1 mock; A2 disease control; A3 unedited-cell control; A4 membrane-V127 (cis only); **A5 secretory graft (thesis)**; A6 recombinant protein; **A7 LNP-mRNA (transient)**; A8 pentosan polysulfate as published positive control benchmark. Primary readout: the proximal(&le;1mm)/distal(&ge;3mm) PrP-res gradient — the spatial signature of trans dominant-negative action, with expected 4-6 mm halo scale from transport modeling. Pre-registered kill-switches include the pivot to acellular vectors if A6&asymp;A5.'))
P('4. Transport engineering (WS-7): three design rules',S_h1)
P(fmt('An ADR solver on heterogeneous porous medium (ECS &alpha;=0.20, &lambda;=1.8; D_eff&asymp;3.9&times;10<super>-11</super> m&sup2;/s; first-order consumption parametrized 10<super>-6</super>-10<super>-5</super> s<super>-1</super>): **Rule 1** containment-ring node spacing 8-12 mm (protection radius r<sub>10%</sub>&asymp;4-6 mm per node); **Rule 2** hydrogel mesh &xi;&ge;5&times;r_p — HA 1-2% releases the secreted agent (D_gel/D_0&ge;0.7), &gt;5% retains it; **Rule 3** mRNA redosing interval &le;7 days keeps the inter-pulse trough &ge;~30-56% of peak. Wave-vs-shield analysis: a 1 mm deposit contains an advancing front within a 4.2-9.5 mm shell for capping/replication ratios 0.1-0.01 — overlapping neighbor shells, and the ratio itself is what G0 measures.'))
P('4-A. In silico humanization of the model: θ* = 0.333 and emergent subtype hierarchy',S_h1)
P(fmt('The prion-spreading kernel of Fornara/Igel et al. (iScience 2024; code Zenodo 11093945) was ported (mean-field, logistically bounded) and coupled to the V127&Delta;GPI capping term as substrate competition (free fraction (1/(1+&kappa;c))&sup2;). **Clock humanization:** matching the simulated doubling time to the human organoid anchors of Groveman 2019 (eclipse clearance 25-28 dpi; de novo production from 35 dpi; titer at 169 dpi: MV2 = 2.13&times;10&#8309; vs MV1 = 1.69&times;10&sup3; SD50/mg) yields 1 simulation unit = 144 real days (human doubling time &asymp; 12.1 d); one simulation spans &asymp;24 months of tissue disease — covering the entire G0 observation window. **Containment threshold:** with humanized clock and seed, the advancing front is contained at &theta; &le; 0.333 (&kappa; = 2; R 2.83&rarr;0.82 mm), monotonically to near-extinction at &kappa; = 32 (R 0.70 mm; biomass ratio 2.1&times; seed). The humanized threshold is *more favorable* than the murine-parameterized one (v2: &theta;*&asymp;0.20): the therapeutic window widens under human kinetics.'))
P(fmt('**Emergent validation — subtype hierarchy reproduced without fitting (the key reviewer-facing result):** seeding the model with MV2-like vs MV1-like initial loads (ratio 126&times;, per Groveman titer ratio) reproduces, unprompted, the qualitative hierarchy of the source data — MV2-like: aggressive growth, high final titer (the only Western-blot-positive subtype in Groveman); MV1-like: baseline also propagates (consistent with persistent RT-QuIC positivity of MV1 organoids) yet is contained by the same &kappa; = 4 with a larger margin (R 0.69 vs 0.78 mm). The order MV2 &gt; MV1 in aggressiveness **emerged from the ported rates and was never fitted to that endpoint** — behavioral validation of the port, distinct from curve-fitting. Pre-registered G0 prediction (locked in repository commits prior to any wet-lab data): if the &theta; measured in infected human organoids is &lt; 0.33, the V127&Delta;GPI shield contains the front in situ; containment/halo readouts expected 90-120 days post-seeding; ring spacing 8-12 mm (Section 4); assay-independent coverage of the observation window by a single simulation run.'),S_abs)
P('6. Regulatory analogy map: nothing unprecedented is being asked',S_h1)
rows=[['Program pillar','Approved precedent in sister disease'],
['Chronic intrathecal redosing','SMA — nusinersen (2016), years of safety in children'],
['Accelerated approval via biomarker in lethal genetic neurodegeneration','SOD1-ALS — tofersen (FDA 2023, NfL endpoint; sponsor also runs the prion ASO program)'],
['Cell grafts in human brain','Parkinson — dopaminergic progenitor trial (Lund, 2026)'],
['Cell-as-protein-factory','Parkinson — GDNF-delivering grafts (MJFF-funded)'],
['Dominant stabilization of a misfolding-prone native protein','ATTR amyloidosis — tafamidis'],
['Substrate lowering','ATTR/SMA — ASO/RNAi class']]
tb=Table([[Paragraph(fmt(a),S_body) for a in r] for r in rows],colWidths=[7.2*cm,9.3*cm])
tb.setStyle(TableStyle([('GRID',(0,0),(-1,-1),0.4,HexColor('#bbbbbb')),('BACKGROUND',(0,0),(0,0),HexColor('#e8f2ec')),('BACKGROUND',(0,0),(0,-1),HexColor('#f4f8f5')),('VALIGN',(0,0),(-1,-1),'TOP'),('FONTSIZE',(0,0),(-1,-1),8.6)]))
story.append(tb);SP(4)
P(fmt('The program therefore requests the **conjunction of approved categories**, not a new category — the central de-risking argument for sponsors and agencies.'))
P('5. Probability model for the organoid gate: pre-registered expectations',S_h1)
P(fmt('Because the gate is pre-registered, its expected outcomes should be too. We decompose the probability that at least one active arm meets the go criterion (&ge;50% proximal PrP-res reduction with a proximal&gt;distal gradient) using named, referenced factors — every number below is either cited, derived from cited data, or our own declared estimate.'),S_body)
P('5.1 The mechanism is settled; the assay is the question',S_h2)
P(fmt('Four independent evidence lines establish the molecular mechanism: transgenic V127/V127 mice are resistant to all tested strains including vCJD [2]; co-expressed G126V (murine homolog) prevents and suppresses established infection dose-dependently across natural and artificial strains [3]; recombinant anchorless V127 retains potent dominant-negative activity in trans [3]; and systemic AAV delivery of anchorless V127 extends survival ~50 days in vivo [4]. Treating their failure as independent events, the residual probability that the mechanism itself is artifactual is &lt;0.01%. The gate therefore measures assay sensitivity and delivery, not mechanism validity.'))
P('5.2 Assay sensitivity is anchored by a positive control',S_h2)
P(fmt('Pentosan polysulfate — an agent with a weaker and less mechanistically specific rationale than anchorless V127 — produced measurable, paradigms-consistent effects in this exact platform (prophylactic-like and therapeutic-like delays [12]). A signal was detectable with a weaker agent, bounding our readout false-negative risk (readout variability, seeding heterogeneity) at ~18%; residual organoid-to-organoid variability adds ~12% strain-dependence risk [3,11]. Combined assay-reliability: ~0.72.'))
P('5.3 Three shots with a shared core and one independent',S_h2)
P(fmt('Arms A5 (secretory graft) and A7 (LNP-mRNA) share their principal unknown — whether in-situ concentration reaches the dominant-negative threshold &theta; (dose-dependence is documented [3] but no absolute K<sub>m</sub> exists). We estimate shared failure at 0.55 (secretion rate and transfection efficiency both could under-deliver; graft survival risk ~0.22 partially mitigated by NPC precedent [13]). Arm A6 (recombinant protein) does not share this risk: dose is a free variable, directly titratable as in [3]; its residual risk is medium stability (~0.25). Assuming conditional independence given the assay works, the probability that all three arms fail is 0.55&times;0.25&asymp;0.14.'))
P('5.4 A geometric argument specific to the organoid',S_h2)
P(fmt('Cerebral organoids grow to 3-4 mm diameter [42] (2-4 mm in routine protocols), i.e. radii of 1.5-2 mm. The transport model (Section 4) gives a protective length scale &ell;=&radic;(D/k)&asymp;3.6 mm for the central parameter case — larger than the entire organoid. Unlike the clinical geometry, where node spacing is the binding constraint, the organoid sits wholly inside a single protective halo: any agent that diffuses at all will reach every cell, and the proximal/distal gradient measures the real spatial scale rather than risking a false negative from under-coverage. This is a structural, not statistical, advantage of the gate.'))
P('5.5 Net expectations and their uses',S_h2)
rows=[['Outcome','P','What it triggers'],
['GO &ge;1 arm (pre-registered criterion)','0.62','advance to G1 (humanized mouse); vector selected by best arm'],
['&mdash; of which A6 protein-driven','0.65','pivot to acellular program (faster, cheaper route)'],
['&mdash; of which A5 secretor-driven','0.50','cellular program proceeds as designed'],
['&mdash; of which A7 mRNA-driven','0.42','opens compassionate-use route for sporadic CJD'],
['NO-GO (all arms fail)','0.38','publish as characterization of the threshold + gradient; halt line with named cause'],
['G1 success conditional on GO','0.65','organoid&rarr;mouse transfer supported by existing Tg and AAV data'],
['G1 success absolute','0.40','program-level probability of reaching clinical candidate']]
tb2=Table([[Paragraph(fmt(a),S_body) for a in r] for r in rows],colWidths=[8.6*cm,1.6*cm,6.3*cm])
tb2.setStyle(TableStyle([('GRID',(0,0),(-1,-1),0.4,HexColor('#bbbbbb')),('BACKGROUND',(0,0),(-1,0),HexColor('#e8f2ec')),('VALIGN',(0,0),(-1,-1),'TOP'),('FONTSIZE',(0,0),(-1,-1),8.6)]))
story.append(tb2);SP(4)
P(fmt('For context, typical preclinical therapeutic hypotheses enter first gate testing at 20-40% success; our expectation is higher because the mechanism is validated four levels below the assay and the assay itself has a published positive control. The dominant residual unknown (&theta;) is a measured output of the experiment, not an assumption: whatever the result, G0 publishes.'),S_body)

P('7. Ethics and limitations',S_h1)
P(fmt('Population: presymptomatic genetic carriers (autologous, time-permissive) with compassionate sporadic use only via the acellular mRNA vector. Falsified or retracted evidence is excluded by rule (e.g., minocycline/FK506 hamster study, retracted 2020; minocycline also confounds NfL interpretation). Limitations: transport parameters are parametric sweeps pending G0 measurement; organoid readouts proxy, not predict, clinical slowing; structured probability estimates (significant slowing 30-45%) are not trial data.'))
P('6. Bayesian success estimates by analogy (pre-registered frame)',S_h1)
P(fmt('To make program-level claims falsifiable before data, we fit a structured Bayesian model (Beta/Jeffreys priors, Monte Carlo 200k) weighting historical successes/failures of nine structural analogs by similarity-squared: SOD1-ASO approval (1/1, sim 0.85), TTR stabilization approval (1/1, 0.80), **failed antiprion clinical candidates (0/6, 0.55 — the negative analog)**, the running prion-ASO program (0/1, 0.90), organoid clinical predictivity (4/5, 0.70), neural cell grafts in human brain (1/3, 0.75), and CNS vector classes (AAV 3/20, ASO 3/5, LNP-mRNA 0/2). Results: P(organoid gate GO) = **36.6% [90% CrI 14.6-60.5]**; P(clinically significant slowing, marginal from today) = **5.0% [0.4-13.6]**; P(full regulatory approval) = **0.3% [0-1.1]**. These marginal estimates coexist with, and do not contradict, conditional program estimates (30-45% slowing GIVEN mechanism and vector success); sensitivity sweeps (&plusmn;0.15 similarity; inter-gate correlation &rho;=0.4) move outcomes by <1.3pp, indicating robustness. The analysis formally identifies the organoid gate as the cheapest information purchase available (EVPI &asymp; +2.6pp per USD 60-160k equivalent).'))
P('7. Concluding synthesis — the fractal collapse of uncertainty',S_h1)
P(fmt('The same triad recurs at every scale of this program — established fact &rarr; design implication &rarr; missing evidence = next gate. Zooming from molecule to program: the molecular layer is closed (8/8 findings published, nothing refuted); the cellular layer concentrates one open question (does the halo function in tissue?); the transport layer is self-tested and its free parameter is precisely what the organoid measures; the program layer holds only execution risk. **The entire residual uncertainty of the program condenses into a single unmeasured event: whether anchorless V127, delivered by any vector, generates a containment gradient in infected human tissue.** One ten-month organoid experiment adjudicates it. We solicit partnership for exactly that measurement — and nothing else requires belief.'))
P('References (selection)',S_h1)
refs=['Asante EA, et al. Nature. 2015;522:478-481.','Mead S, et al. N Engl J Med. 2009;361:2056-2065.','Gatdula JRP, et al. bioRxiv 2026.02.17.703887 (PMID 41757113).','Zerbes T, et al. Preprint 2026 (PMC13041815).','Hosszu LP, et al. Commun Biol. 2020;3:580.','Zheng Z, et al. Sci Rep. 2018;8:11458.','Mallucci G, et al. Science. 2003;302:871-874.','Raymond GJ, et al. JCI Insight. 2019;4:e131175.','Minikel EV, et al. Nucleic Acids Res. 2020;48:10615-10631.','Mead S, et al. Lancet Neurol. 2022 (PRN100).','Groveman BR, et al. Acta Neuropathol. 2019;137:987-996.','Groveman BR, et al. Sci Rep. 2021;11:5160 (PPS).','Williams K, et al. Stem Cell Res Ther. 2023;14:348.','Abud EM, et al. Neuron. 2017;94:278-293.','Han X, et al. PNAS. 2019;116:10441-10446.','Hu X, et al. Nat Biotechnol. 2024;42:807-815.','Pavan C, et al. Cell Stem Cell. 2025 (cloaked neural graft).','Liang Y, et al. Biomaterials. 2013;34:3948-3957.','Xue Y, et al. Adv Mater. 2025 (PMID 40317512).','Dong S, et al. 2025 (P3B LNP).','Thorne RG, Nicholson C. PNAS. 2006;103:8217-8222.','Masel J, Jansen VA, Nowak MA. Biophys Chem. 1999;77:139-152.','FDA. Tofersen accelerated approval (SOD1-ALS), 2023.','Spinraza (nusinersen) approval, 2016.','Bengtsson SL, et al. (Lund) Parkinson cell transplant trial, 2026.','Smid J, et al. Dement Neuropsychol. 2007 (first Brazilian E200K).','Coelho T, et al. (tafamidis, ATTR).','Relaño-Ginés A, et al. PLoS Pathog. 2013;9:e1003485.','Ginhoux F, et al. Science. 2010;330:841-845.','Sorrells SF, et al. Nature. 2018;558:253-258.','Gomez-Nicola D, et al. Brain. 2014;137:2312-2328.','De Lucia C, et al. 2016 (microglia-neurogenesis).','Jalland CMO, et al. Sci Rep. 2016;6:37844.','Elder JB, Lonser RR, et al. J Neurosurg. 2025;143:1431-1441.','Krauze MT, et al. J Neurosurg. 2005 (step cannula).','Cheng S, et al. Sci Rep. 2015;5:10535 (minocycline).','Gentile JE, et al. 2024 (minocycline confounds NfL).','Retraction: Shah SZA, et al. Neurotherapeutics 2017 (retracted 2020).','Lund/Laugsand — see NCT registry (Parkinson cell therapy).','Shibuya S, et al. (review).','Kim J, et al. 2025 (universal iPSC).']
refs.append('Qian X, et al. Brain organoids: advances, applications and challenges. Nat Biotechnol. 2019;37:1393-1394.')
for i,r in enumerate(refs,1): P(f'[{i}] {fmt(r)}',S_ref)

doc=SimpleDocTemplate(OUT,pagesize=A4,leftMargin=2*cm,rightMargin=2*cm,topMargin=1.8*cm,bottomMargin=1.8*cm,title='PrP-V127 as a Modular Antiprion Platform',author='Consórcio Príons/Quest 003')
doc.build(story)
print('PDF OK:',OUT,os.path.getsize(OUT),'bytes')
