# -*- coding: utf-8 -*-
"""PT completo — tradução integral do preprint v4."""

PT={
 'title':'PrP-V127 como Plataforma Modular Antipríon: um Programa de Ciência Aberta da Genética Populacional às Predições Pré-Registradas em Organoides, ao Dimensionamento de Transporte em Escala Tecidual e aos Precedentes Regulatórios para a Doença de Creutzfeldt-Jakob',
 'subtitle':'Preprint completo · Consórcio de ciência aberta · DeepScientist Quest 003 · 26/08/2026',
 'authors':'Consórcio de Príons e Engenharia Molecular — código, dados e auditoria abertos (40+ commits auditados em git)',
 'footer':'Plataforma Antipríon PrP-V127 — preprint do consórcio v4.0 (PT)',
 'footer2':'p. %(p)d — preprint, sem revisão por pares',
 'abstract_h':'Resumo',
 'abstract':'As doenças priônicas são universalmente fatais, com seis candidatos clínicos fracassados em três décadas. Apresentamos um programa completo, auditado e de ciência aberta de desenvolvimento terapêutico, convertendo a variante humana PrP-V127 — selecionada pela epidemia de kuru, que confere resistência priônica completa e estruturalmente compreendida, atuando como inibidor dominante-negativo potente e dose-dependente, inclusive como proteína secretada sem âncora — em uma terapia implantável. O programa integra sete frentes independentes: (i) revisão auditada com 42 referências, corrigindo erros de citação recorrentes, com um estudo retraído excluído por regra; (ii) desenho dirigido por refutação — cada alegação refutada (linhagem microglial, "fábrica" SVZ, janela da forma esporádica) gerou ramos de solução ancorados (co-enxerto de micróglia de iPSC, plataforma secretora, LNP-mRNA intratecal); (iii) um portão de organoide (G0) pré-registrado com oito braços, interruptores de morte e controle positivo publicado (PPS); (iv) engenharia de transporte em escala tecidual — solver ADR auto-testado (conservação de massa 100%, erro de Thiele 0,5%) produzindo três regras de desenho falsificáveis (espaçamento do anel 8-12 mm; malha do hidrogel ≥ 5× o raio da proteína; redose de mRNA ≤ 7 dias) e casca de contenção de 4,2-9,5 mm; (v) ensaio in silico humanizado: o kernel estocástico de espalhamento do iScience-2024, portado e acoplado ao capping V127 como competição de substrato, calibrado às âncoras de organoide humano (tempo de duplicação 12,1 dias; 1 unidade sim = 144 dias), localizando o limiar de contenção em θ* = 0,333 — mais favorável que os parâmetros murinos — com a hierarquia de subtipos MV2>MV1 emergindo sem ajuste; (vi) estimativa bayesiana ponderada por dez análogos históricos incluindo as seis falhas priônicas (aprovação do portão organoide 36,6% [14,6-60,5]; desaceleração clínica significativa 5% estruturado-a-45%); (vii) mapa regulatório mostrando que cada pilar tem precedente aprovado em proteopatia irmã (nusinersen, tofersen, tafamidis, Lund-2026). O programa é publicado como pipeline completo, pré-registrado e falsificável; a execução úmida requer um ciclo de organoide (~10 meses).',
 'keywords':'Palavras-chave: doenças priônicas; Creutzfeldt-Jakob; G127V; dominante-negativo; organoides cerebrais; entrega por convecção; modelagem reação-difusão; desenvolvimento bayesiano de fármacos; pré-registro; ciência aberta.',
 's1_h':'1. Introdução — um programa, não um candidato',
 's1':[
  'As doenças priônicas humanas são raras, rapidamente progressivas e universalmente fatais; a forma esporádica mata em 6-8 meses do início, e trinta anos de terapias candidatas produziram seis fracassos clínicos e zero aprovações. A resposta convencional — uma molécula, uma cascata de screening, um paper — fracassou repetidamente. Adotamos abordagem distinta: tratar o próprio desenvolvimento como objeto de engenharia, com a mesma disciplina de falsificabilidade aplicada ao programa que se aplica normalmente a um único experimento.',
  'Este preprint documenta um programa completo construído em torno da variante G127V da proteína priônica humana: descoberta como o alelo que protegeu sobreviventes da epidemia de kuru (Mead 2009), comprovada em camundongos transgênicos como conferidora de resistência completa quando bialélica — "tão protetora quanto a deleção do gene" — e inibidora dose-dependente dominante-negativa da propagação selvagem (Asante 2015), estruturalmente explicada por duas linhas independentes (Zheng 2018; Hosszu 2020) e validada como princípio terapêutico secretado e sem âncora in vitro e em roedores em 2026 (Gatdula; Zerbes). Cada elemento do núcleo molecular está publicado e verificado; os problemas abertos são de engenharia — entrega, escala e probabilidade honesta.',
  'Três compromissos organizam tudo o que segue: (1) nada entra no registro sem verificação de fonte (trilha de auditoria com uma exclusão de retratação); (2) toda alegação quantitativa que possa ser simulada é simulada antes de ser comprada na bancada; (3) todo experimento é desenhado com desfechos pré-registrados e falsificáveis. O resultado é um programa em que o único portão úmido restante (G0, um ciclo de organoide) chega com predições numéricas já travadas em controle de versão.'],
 's2_h':'2. Arquitetura do programa e disciplina de auditoria',
 's2_p':'Sete frentes de trabalho, cada uma documentada independentemente, versionada e referenciada ao grafo vivo de conhecimento (40 nós, 51 arestas) que rastreia o status de cada achado (válido/inválido/cinza-claro/cinza-escuro) ao longo das versões:',
 's2_t1':[['Frente','Artefato','Papel no programa'],
  ['WS-A','Revisão auditada (42 refs)','Núcleo molecular; correções de citação; regra de exclusão de retratação'],
  ['WS-B','Refutações e ramos (R1-R8)','Cada alegação refutada → ramo ancorado com critério de morte'],
  ['WS-G0','Protocolo organoide 8 braços','O único portão úmido decisivo, pré-registrado'],
  ['WS-7','Solver de transporte (ADR)','Regras espaciais: anel, hidrogel, redose; casca de contenção'],
  ['WS-9','Ensaio in silico humanizado','Kernel de espalhamento + capping V127; relógio calibrado a organoides humanos'],
  ['WS-8','Estimativas bayesianas','Probabilidade com variância de 10 análogos históricos'],
  ['WS-6','Mapa regulatório','Nenhuma categoria inédita; cada pilar tem precedente aprovado']],
 's2_tn':'Tabela 1. Inventário de frentes. Todos os artefatos estão em trilha pública auditável (git), com timestamps anteriores a qualquer dado úmido.',
 's2b_h':'2.1 Protocolo de verificação',
 's2_t2':[['Regra','Implementação'],
  ['Verificação de fonte antes de adoção','Toda alegação externa buscada e lida; 3/3 rascunhos externos auditados — 11/15, depois 2 links quebrados, depois 6/6 válidos (melhora documentada)'],
  ['Exclusão de retratação','Shah 2017 (minociclina/FK506, retraído 2020) banido por regra; minociclina também confunde NfL (Gentile 2024) → critério de exclusão de coorte'],
  ['Registro de adjudicação','Cada alegação submetida classificada aceita/ajustada/rejeitada com motivos'],
  ['Pré-registro','Predições do G0 (θ*, halo, calendário) travadas em commits antes de qualquer dado úmido']],
 's3_h':'3. O ativo molecular e suas restrições de engenharia',
 's3':[
  'G127V é a única variante da proteína priônica humana com resistência completa comprovada in vivo: camundongos V127 bialélicos resistem a todas as cepas testadas, enquanto heterozigotos — embora resistentes ao kuru e à DCJ clássica — foram infectados por vCJD (Asante 2015). Esta única nuance dita a primeira restrição: **expressão bialélica ou entrega sem âncora são obrigatórias**; um enxerto heterozigoto de membrana reproduziria o escudo permeável.',
  'O mecanismo dominante-negativo atua em cis (dentro das células expressoras) e — conforme estabelecido em 2026 — em trans: a V127 recombinante sem âncora retém potente atividade dominante-negativa contra PrP selvagem co-expresso em sistemas celulares (Gatdula), e a entrega sistêmica por AAV de V127 sem âncora estende a sobrevida ~50 dias em roedor (Zerbes). A proteção persiste após cessar a expressão do transgene (Gatdula), o que converte desenhos de "fábrica permanente" de exigência em opção e viabiliza vetores transientes (mRNA).'],
 's3_t1':[['Achado','Evidência e status'],
  ['Seleção pelo kuru de G127V','Mead 2009 NEJM — VÁLIDO (prova populacional de princípio)'],
  ['V127 bialélico = resistência completa','Asante 2015 Nature — VÁLIDO; permeabilidade vCJD do heterozigoto = restrição vinculante'],
  ['Dominante-negativo dose-dependente','Asante 2015; Gatdula 2026 — VÁLIDO (cis e trans)'],
  ['Base estrutural (dímeros estáveis, restrição de loop)','Zheng 2018; Hosszu 2020 — VÁLIDO (dupla)'],
  ['V127 sem âncora in vivo (+50 d, AAV)','Zerbes 2026 preprint — VÁLIDO (prova de conceito em roedor)'],
  ['Linhagem NSC→micróglia','Ginhoux 2010 — REFUTADO; corrigido para co-enxerto de micróglia-iPSC (Abud 2017)'],
  ['"Fábrica" SVZ autorrenovável','Sorrells 2018; Relaño-Ginés 2013 — REFUTADO como especificado; reenquadrado como depósito de liberação lenta']],
 's4_h':'4. Desenho dirigido por refutação: de becos sem saída a ramos',
 's4_p':'Um programa ganha credibilidade pelo que refuta. Cada falha da concepção original foi convertida em ramo de solução explícito com evidência ancorada, probabilidade, portão e critério de morte:',
 's4_t1':[['#','Alegação refutada/restrita','Ramo adotado (evidência · P · kill)'],
  ['R1','NSCs geram micróglia','Co-enxerto iPSC-micróglia (Abud 2017; De Lucia 2016) — RESOLVIDO'],
  ['R2','Fábrica SVZ permanente','Depósito liberação lenta (padrão) · multi-nó · **LNP-mRNA intratecal** (Xue 2025: ~30% neurônios; 0,35-0,50; kill: expressão < nível DN >7 d)'],
  ['R3','Contenção de frente sólida <20%','Anel em nós de rede + ponte ASO · base mRNA + pico focal (0,40-0,55)'],
  ['R4','Janela esporádica vs manufatura celular','E200K/D178N autólogo (padrão, 0,80) · banco hipoimune (Han 2019; Hu 2024; 0,50-0,60; G1.5) · **mRNA: manufatura em dias** (0,60-0,70 compassivo)'],
  ['R5','Sobrevida do enxerto 15-30% (doença ativa)','**Carreador hidrogel HA pró-sobrevivência** (Liang 2013; Nih 2017; 0,45) · imunomodulação periop proibida (lit. retraída; Cheng 2015)'],
  ['R6','Rejeição de aloenxerto','Hipoimune HLA-KO+CD47 (Hu 2024 macaco; Pavan 2025 neural) · banco HLA-homozigoto (2ª linha)'],
  ['R7','Regeneração do núcleo morto','REENQUADRADO: resgatar penumbra + conter progressão (Williams 2023) — núcleo fora do escopo'],
  ['R8','Margem DTI < microfocos','Calibração de margem RT-QuIC intraoperatória · IHC rápida · PET-tracer registrado como lacuna do campo']],
 's4_p2':'Consequência de portfólio: três vetores (célula secretora · proteína recombinante · LNP-mRNA) mirando um mecanismo, testados lado a lado no mesmo portão organoide — o portão decide *qual vetor escala*, não apenas sim/não.',
 's5_h':'5. Os três vetores de entrega',
 's5_p':'',
 's5_t1':[['Dimensão','Enxerto NSC secretor','Proteína recombinante','LNP-mRNA (intratecal)'],
  ['Manufatura','meses (GMP celular)','semanas','**dias**'],
  ['Controle espacial','anel focal + depósito (CED)','perfil de infusão','LCR global + pico focal'],
  ['Durabilidade','meses-anos (depósito)','dias por dose','dias por dose; redose ≤7 d (regra 3 do WS-7)'],
  ['Caminho regulatório','terapia celular ATMP','biológico','fármaco ácido nucleico (sem cirurgia grau 0)'],
  ['Esporádico compassivo','inviável no prazo','viável','**viável (0,5-0,7)**']],
 's5_p2':'**Nota:** os três vetores são complementares, não concorrentes: o mRNA fornece ponte e cobertura compassiva; o enxerto celular fornece permanência e suporte trófico local (NPCs restauram eletrofisiologia em organoides infectados independentemente da contenção — Williams 2023).',
 's6_h':'6. O portão organoide (G0): oito braços, pré-registrado',
 's6_p':'A plataforma está validada (infecção: Groveman 2019; screening com PPS: Groveman 2021; semeadura celular: Williams 2023); nenhum agente V127 jamais entrou em organoide. Braços:',
 's6_t1':[['Braço','Intervenção','Testa'],
  ['A1/A2','mock · controle doença','baselines'],
  ['A3','NSC não editada','efeito apenas trófico'],
  ['A4','V127 bialélico de membrana','cis + justacrina'],
  ['A5','**enxerto secretor V127ΔGPI**','a tese: halo trans difusível'],
  ['A6','proteína V127ΔGPI recombinante','agente sem veículo celular'],
  ['A7','LNP-mRNA (transiente)','rota acelular; janela de redose'],
  ['A8','controle positivo PPS','benchmark publicado (mesma plataforma)']],
 's6_p2':'Leitura primária: gradiente PrP-res proximal(≤1 mm)/distal(≥3 mm) — a assinatura espacial da ação trans. GO/NO-GO pré-registrado, incluindo a regra de pivô: se A6≈A5, o programa migra para vetores acelulares. Amostra: n=8 organoides/braço; >80% poder para Δ≥50% a CV~30% (Holm).',
 's7_h':'7. Engenharia de transporte (WS-7): da opinião aos números',
 's7':[
  'Entrega é onde candidatos priônicos historicamente morrem (o PPS nunca atingiu níveis no SNC humano). Resolvemos o problema de transporte quantitativamente antes de qualquer bancada: solver de advecção-difusão-reação em meio poroso heterogêneo, com parâmetros de ECS de medidas in vivo humanas (α=0,20; λ=1,8; Thorne & Nicholson 2006) e consumo de 1ª ordem parametrizado 10⁻⁶-10⁻⁵ s⁻¹. Auto-testes: conservação de massa 100,0%; comprimento de Thiele vs analítico com 0,5% de erro.',
  'O halo de proteção de um depósito segue o clássico problema de Thiele da engenharia química: comprimento de penetração ℓ=√(D/k). Para o caso médio (k=3×10⁻⁶ s⁻¹), ℓ≈3,6 mm e r₁₀% = 4,2-5,8 mm por nó; o regime estacionário estabelece em ~4 dias, de modo que leituras de 90 dias no organoide operam em equilíbrio profundo.'],
 's7_rh':'Tabela 2 — Varredura de Thiele (r10% em mm)',
 's7_t1':[['k (s⁻¹)','D=5e-12','D=3,9e-11','D=1e-10'],
  ['1×10⁻⁶','3,4','5,1','6,0'],
  ['3×10⁻⁶','2,7','4,2','5,0'],
  ['1×10⁻⁵','2,1','3,2','3,9']],
 's7_rules':'As três regras de desenho (cada uma falsificável em G0/G1)',
 's7_t2':[['#','Regra','Derivação'],
  ['1','Espaçamento de nós do anel 8-12 mm','halo 4-6 mm por nó; cascas vizinhas se sobrepõem'],
  ['2','Malha do hidrogel ≥ 5× raio da proteína (HA 1-2% ok; >5% retém secretoma)','modelo de obstrução exp(-1,8ξ/r); resolve tensão carreador-vs-liberação'],
  ['3','Intervalo de redose mRNA ≤7 dias','vale entre pulsos ≥30% do pico; 10-14 d abre vales de exposição']],
 's8_h':'8. O ensaio in silico humanizado (WS-9): onde vive o limiar',
 's8_intro':[
  'Portamos o kernel estocástico de espalhamento reação-difusão de Fornara/Igel et al. (iScience 2024; código público, Zenodo 11093945) para forma determinística mean-field (limitada logisticamente; limitação declarada na §12) e o acoplamos ao mecanismo de capping V127 como **competição de substrato**: a fração de substrato livre (1/(1+κc))² multiplica toda taxa de templating — a forma funcional da exclusão competitiva, ancorada em Asante (dose-dependência) e Hosszu (base estrutural).',
  'A semântica das reações foi decodificada linha a linha da implementação original: crescimento templado B_a→B_a+1, duplicação autocatalítica do pool C→2C (o motor da replicação), fragmentação B_a→B_a-1+C, nucleação, condensação/descondensação, difusão por classe e silenciamento local de templating por UPR.'],
 's8_eq':'∂P/∂t = D∇²P + R(P; tp, freeS) − perdas   ;   freeS(r) = (1/(1+κ·c(r)))²,  c(r)=e^(−r/ℓ)',
 's8_t1':[['Elemento','Implementação'],
  ['Kernel','Fornara/Igel iScience 2024 (port mean-field; estocasticidade declarada como limitação)'],
  ['Capping (este trabalho)','competição de substrato sobre todas as taxas de templating — a exclusão competitiva do protocolo original, com forma quantitativa'],
  ['Calibração do relógio','âncoras de organoide humano (Groveman 2019): duplicação ≈12,1 dias → 1 unidade sim = 144 dias'],
  ['Domínios','96×96, t=5 unidades (≈24 meses de tempo tecidual; cobre toda a janela do G0)']],
 's8_rh':'8.1 Resultados — limiar e hierarquia emergente de subtipos',
 's8_clock':'Com relógio e semente humanizados, a frente é contida em θ ≤ 0,333 (κ=2; R 2,83→0,82 mm), monotonicamente até quase-extinção em κ=32 (R 0,70 mm; razão de biomassa 2,1× a semente). O limiar humanizado é *mais favorável* que o murino (v2: θ*≈0,20): a cinética humana alarga a janela terapêutica.',
 's8_t2_h':['Âncora (Groveman 2019)','Título (SD50/mg)','Duplicação / razão','Contenção'],
 's8_emerg':'**Validação emergente (sem ajuste).** Semear cargas iniciais MV2-like vs MV1-like (razão 126×, pela razão de títulos publicada) reproduz, sem instrução, a hierarquia da fonte: MV2-like cresce agressivamente até título alto (o único subtipo Western-blot-positivo nos dados-fonte); MV1-like também propaga (consistente com RT-QuIC persistentemente positivo) mas é contido pelo mesmo κ=4 com margem maior (R 0,69 vs 0,78 mm). A ordem MV2>MV1 **emergiu das taxas portadas e jamais foi ajustada para esse desfecho** — validação comportamental, distinta de curve-fitting.',
 's8_fig':'Figura 1. Curva de resposta in silico: raio final da frente vs θ (relógio humanizado). A bifurcação entre propagação e contenção está em θ* = 0,333.',
 's8_pred':'**Predição pré-registrada do G0 (travada em controle de versão antes de qualquer dado úmido):** se θ_medido < 0,33, o escudo V127ΔGPI contém a frente em organoides humanos infectados; leituras de contenção esperadas 90-120 dias pós-semeadura; escala de halo 4-6 mm; espaçamento do anel 8-12 mm; uma simulação cobre toda a janela de observação.',
 's9_h':'9. Estimativas bayesianas: honestidade sobre probabilidade',
 's9':[
  'Otimismo estruturado (nível-desenho: mecanismo correto, portfólio de vetores) e empirismo histórico (o retrospecto do campo) são reportados lado a lado — o programa opera sob ambas as lentes, e toda pergunta de audiência mapeia para uma delas.',
  'O modelo ponderado por análogos (dez análogos, incluindo as seis falhas priônicas como análogo negativo e o programa-irmão exato ION717 como pendente 0/1) resulta: aprovação do portão organoide 36,6% [14,6-60,5]; **desaceleração clínica significativa 5,0% [0,4-13,6]** sob o prior histórico, contra a banda estruturada 30-45%. Ambos publicados; nenhum escondido.'],
 's9_t1':[['Evento','Bayesiano (prior histórico)','Estruturado (prior de desenho)'],
  ['Portão G0 passa','36,6% [14,6-60,5]','40-50% (predição pré-registrada)'],
  ['Desaceleração clínica significativa','**5,0% [0,4-13,6]**','30-45%'],
  ['Compassivo esporádico via mRNA','—','50-70%'],
  ['Condicional à confirmação plena G0-G2','40-55%','ver escada §13']],
 's10_h':'10. Mapa de analogias regulatórias',
 's10_p':'Nenhum pilar do programa solicita categoria regulatória inédita:',
 's10_t1':[['Pilar do programa','Precedente aprovado (proteopatia irmã)'],
  ['Redose intratecal crônica','SMA — nusinersen (2016), anos de segurança pediátrica'],
  ['Aprovação acelerada por biomarcador em neurodegeneração genética letal','ALS-SOD1 — tofersen (FDA 2023, endpoint NfL; mesma classe de sponsor do programa ASO priônico)'],
  ['Enxertos celulares em cérebro humano','Parkinson — ensaio de progenitores dopaminérgicos (Lund, 2026)'],
  ['Célula como fábrica de proteína','Parkinson — enxertos entregadores de GDNF (financiado MJFF)'],
  ['Estabilização dominante de proteína nativa propensa a misfolding','Amiloidose ATTR — tafamidis'],
  ['Redução de substrato','ATTR/SMA — classe ASO/RNAi']],
 's11_h':'11. Ética, população e governança',
 's11':[
  'O caminho estruturado passa por portadores genéticos pré-sintomáticos (E200K — primeiro kindred brasileiro relatado 2007; D178N, P102L), onde manufatura autóloga é viável no prazo e o consentimento é sereno; uso compassivo esporádico apenas via rota acelular mRNA. O esqueleto regulatório brasileiro (CEP→CONEP→Anvisa ATMP) está pré-redigido. Biossegurança: protocolo de cânula coaxial de uso único; descontaminação de instrumentais WHO; o SNC permanece infeccioso post-mortem independentemente do desfecho — contenção de necropsia é parte do protocolo.',
  'Minociclina é excluída da coorte (confunde o endpoint NfL — Gentile 2024); o estudo retraído minociclina/FK506 é banido de citação por regra do programa.'],
 's11_t1':[['Elemento de governança','Implementação'],
  ['Pré-registro','Todas as predições quantitativas travadas em versão antes de dados úmidos'],
  ['Trilha de auditoria','Grafo vivo de 40 nós; toda transição de status commitada com evidência'],
  ['Dados e código','Solvers, ports, notebooks e parâmetros públicos; scripts determinísticos'],
  ['Disciplina de falha','Cada ramo carrega critério de morte; G0 inclui regra de pivô explícita']],
 's12_h':'12. Limitações, com honestidade',
 's12_t1':[['Limitação','Impacto','Mitigação / status'],
  ['Port mean-field (estocasticidade perdida)','Flutuações de extinção e coexistência de cepas ausentes','Port estocástico tau-leaping planejado; kernel original público'],
  ['Parâmetros Igel calibrados p/ TSE, não sCJD humano','Magnitudes ×3-10 incertas; θ adimensional (robusto)','Relógio recalibrado a âncoras humanas; G0 mede θ diretamente'],
  ['κ ↔ concentração real de V127 não mapeado','O elo mais fraco: tradução sim→dose','G0-A6 (braço proteína em dose conhecida) fecha'],
  ['Âncoras Groveman: só MV1/MV2 (não MM1)','Subtipo mais comum sem parâmetros','G0 inclui braço MM1; refit planejado'],
  ['Priors bayesianos esparsos (n=10)','Intervalos largos [0,4-13,6]','Reportados como intervalos, nunca pontos; atualizados a cada portão'],
  ['Sem dados úmidos ainda (tudo in silico + literatura)','Todas as predições são predições','Este é o ponto do pré-registro; um ciclo de organoide decide']],
 's13_h':'13. Síntese conclusiva — o colapso fractal da incerteza',
 's13':[
  'Em quatro escalas (molecular, celular, tecidual, programa) opera a mesma tríade: fato duro → implicação de desenho → evidência que falta = o próximo portão. A camada molecular está fechada (8/8 válidos). A camada celular guarda exatamente uma pergunta aberta — o halo V127 funciona em tecido humano infectado — e essa pergunta é precisamente o que o G0 faz. A camada tecidual se alimenta do G0 (ele mede θ), e a camada de programa carrega apenas risco de execução (financiamento, parceiros, coorte).',
  'Se tudo à frente confirmar, a escada de credibilidade sobe do prior histórico de 5% para 40-55% no primeiro humano e 70-85% após sinal de fase 2 — e o campo ganha sua primeira terapia racionalmente desenhada e integralmente pré-registrada, nascida da genética populacional de uma epidemia de canibalismo, engenheirada em aberto. Se o G0 refutar, dois anos e milhões são poupados, e a própria refutação — pré-registrada, em plataforma com benchmark — é o resultado publicável que o campo priônico não produziu em trinta anos.'],
 'refs_h':'Referências (42, todas verificadas na fonte)',
 'refs':[
  'Mead S, et al. N Engl J Med. 2009;361:2056-2065.','Asante EA, et al. Nature. 2015;522:478-481.',
  'Zheng Z, et al. Sci Rep. 2018;8:11458.','Hosszu LP, et al. Commun Biol. 2020;3:580.',
  'Gatdula JRP, et al. bioRxiv 2026.02.17.703887 (PMID 41757113).','Zerbes T, et al. 2026 (PMC13041815).',
  'Mallucci G, et al. Science. 2003;302:871-874.','Mallucci GR, et al. Neuron. 2007;53:325-335.',
  'Raymond GJ, et al. JCI Insight. 2019;4:e131175.','Minikel EV, et al. Nucleic Acids Res. 2020;48:10615-10631.',
  'Mead S, et al. Lancet Neurol. 2022 (PRN100).','Fornara B, Igel A, et al. iScience 2024 (PMID 39717079; código: Zenodo 11093945).',
  'Groveman BR, et al. Acta Neuropathol. 2019;137:987-996.','Groveman BR, et al. Sci Rep. 2021;11:5160.',
  'Williams K, et al. Stem Cell Res Ther. 2023;14:348.','Abud EM, et al. Neuron. 2017;94:278-293.',
  'Han X, et al. PNAS. 2019;116:10441-10446.','Hu X, et al. Nat Biotechnol. 2024;42:807-815.',
  'Pavan C, et al. Cell Stem Cell. 2025.','Liang Y, et al. Biomaterials. 2013;34:3948-3957.',
  'Nih LR, et al. 2017 (HA-gel iPSC-NPC).','Xue Y, et al. Adv Mater. 2025 (PMID 40317512).',
  'Dong S, et al. 2025 (P3B LNP).','Thorne RG, Nicholson C. PNAS. 2006;103:8217-8222.',
  'Masel J, Jansen VA, Nowak MA. Biophys Chem. 1999;77:139-152.','FDA. Tofersen aprovação acelerada. 2023.',
  'Nusinersen (Spinraza) aprovação. 2016.','Ensaio de transplante celular PD (Lund). 2026.',
  'Smid J, et al. Dement Neuropsychol. 2007 (primeiro E200K brasileiro).','Coelho T, et al. (tafamidis, ATTR).',
  'Relaño-Ginés A, et al. PLoS Pathog. 2013;9:e1003485.','Ginhoux F, et al. Science. 2010;330:841-845.',
  'Sorrells SF, et al. Nature. 2018;558:253-258.','Gomez-Nicola D, et al. Brain. 2014;137:2312-2328.',
  'De Lucia C, et al. 2016 (micróglia-neurogênese).','Jalland CMO, et al. Sci Rep. 2016;6:37844.',
  'Elder JB, Lonser RR, et al. J Neurosurg. 2025;143:1431-1441.','Krauze MT, et al. J Neurosurg. 2005.',
  'Cheng S, et al. Sci Rep. 2015;5:10535.','Gentile JE, et al. 2024 (minociclina confunde NfL).',
  'Nota de retratação: Shah SZA, et al. Neurotherapeutics 2017 (retraído 2020).','Kim J, et al. 2025 (iPSC universal).'],
 'data_h':'Disponibilidade de dados, código e auditoria',
 'data_p':'Todos os artefatos do programa — solvers (auto-testados), o port in silico humanizado com parâmetros, notebooks de animação, dados do grafo de conhecimento (40 nós / 51 arestas com histórico de status), registros de auditoria e todos os documentos intermediários — estão versionados no repositório do consórcio com timestamps anteriores a qualquer dado úmido. Scripts de análise são determinísticos; simulações reproduzem-se dos notebooks publicados. Este preprint é gerado dessas fontes por script de build reprodutível.',
}
